packages:
  - packages/core
  - packages/game
  - packages/ui
  - packages/ui-testing
  - packages/dev-server
  #
  - games/*/game
  - games/*/ui
  - games/*

allowBuilds:
  esbuild: true
  nx: true

minimumReleaseAge: 1440

overrides:
  handlebars: ">=4.7.9"
